In [7]:
import nltk

In [8]:
#파일 불러오기
nltk.corpus.gutenberg.fileids()

['austen-emma.txt',
 'austen-persuasion.txt',
 'austen-sense.txt',
 'bible-kjv.txt',
 'blake-poems.txt',
 'bryant-stories.txt',
 'burgess-busterbrown.txt',
 'carroll-alice.txt',
 'chesterton-ball.txt',
 'chesterton-brown.txt',
 'chesterton-thursday.txt',
 'edgeworth-parents.txt',
 'melville-moby_dick.txt',
 'milton-paradise.txt',
 'shakespeare-caesar.txt',
 'shakespeare-hamlet.txt',
 'shakespeare-macbeth.txt',
 'whitman-leaves.txt']

In [9]:
# shakespeare-hamlet.txt 를 사용!
# nltk.corpus.gutenberg.sents은 마지막 "." 을 기준으로 문장 불러오기
hamlet = nltk.corpus.gutenberg.sents("shakespeare-hamlet.txt")

In [10]:
#타입 확인
type(hamlet), len(hamlet)

(nltk.corpus.reader.util.StreamBackedCorpusView, 3106)

In [11]:
# 앞에서 20개 문장 출력
print(hamlet[:20])

[['[', 'The', 'Tragedie', 'of', 'Hamlet', 'by', 'William', 'Shakespeare', '1599', ']'], ['Actus', 'Primus', '.'], ['Scoena', 'Prima', '.'], ['Enter', 'Barnardo', 'and', 'Francisco', 'two', 'Centinels', '.'], ['Barnardo', '.'], ['Who', "'", 's', 'there', '?'], ['Fran', '.'], ['Nay', 'answer', 'me', ':', 'Stand', '&', 'vnfold', 'your', 'selfe'], ['Bar', '.'], ['Long', 'liue', 'the', 'King'], ['Fran', '.'], ['Barnardo', '?'], ['Bar', '.'], ['He'], ['Fran', '.'], ['You', 'come', 'most', 'carefully', 'vpon', 'your', 'houre'], ['Bar', '.'], ["'", 'Tis', 'now', 'strook', 'twelue', ',', 'get', 'thee', 'to', 'bed', 'Francisco'], ['Fran', '.'], ['For', 'this', 'releefe', 'much', 'thankes', ':', "'", 'Tis', 'bitter', 'cold', ',', 'And', 'I', 'am', 'sicke', 'at', 'heart']]


In [12]:
hamlet[:20]

[['[',
  'The',
  'Tragedie',
  'of',
  'Hamlet',
  'by',
  'William',
  'Shakespeare',
  '1599',
  ']'],
 ['Actus', 'Primus', '.'],
 ['Scoena', 'Prima', '.'],
 ['Enter', 'Barnardo', 'and', 'Francisco', 'two', 'Centinels', '.'],
 ['Barnardo', '.'],
 ['Who', "'", 's', 'there', '?'],
 ['Fran', '.'],
 ['Nay', 'answer', 'me', ':', 'Stand', '&', 'vnfold', 'your', 'selfe'],
 ['Bar', '.'],
 ['Long', 'liue', 'the', 'King'],
 ['Fran', '.'],
 ['Barnardo', '?'],
 ['Bar', '.'],
 ['He'],
 ['Fran', '.'],
 ['You', 'come', 'most', 'carefully', 'vpon', 'your', 'houre'],
 ['Bar', '.'],
 ["'",
  'Tis',
  'now',
  'strook',
  'twelue',
  ',',
  'get',
  'thee',
  'to',
  'bed',
  'Francisco'],
 ['Fran', '.'],
 ['For',
  'this',
  'releefe',
  'much',
  'thankes',
  ':',
  "'",
  'Tis',
  'bitter',
  'cold',
  ',',
  'And',
  'I',
  'am',
  'sicke',
  'at',
  'heart']]

In [13]:
# 문장 사전 만들기
data = []
#문장 개수만큼 반복(20번)
for line in hamlet[:20]:
    # 각 문장에서 단어들을 word에 할당
    for word in line:
        # 단어들이 data 내부에 없고 알파벳이나 숫자라면
        if word.isalnum() and word not in data:
            #문장사전에 추가한다
            data.append(word)
#문장 사전 출력
print(data)
#문장 사전 길이 출력
len(data)

['The', 'Tragedie', 'of', 'Hamlet', 'by', 'William', 'Shakespeare', '1599', 'Actus', 'Primus', 'Scoena', 'Prima', 'Enter', 'Barnardo', 'and', 'Francisco', 'two', 'Centinels', 'Who', 's', 'there', 'Fran', 'Nay', 'answer', 'me', 'Stand', 'vnfold', 'your', 'selfe', 'Bar', 'Long', 'liue', 'the', 'King', 'He', 'You', 'come', 'most', 'carefully', 'vpon', 'houre', 'Tis', 'now', 'strook', 'twelue', 'get', 'thee', 'to', 'bed', 'For', 'this', 'releefe', 'much', 'thankes', 'bitter', 'cold', 'And', 'I', 'am', 'sicke', 'at', 'heart']


62

In [14]:
# 문장들중 4번째 문장을 sent1 에 할당
sent1 = hamlet[3]
sent1


['Enter', 'Barnardo', 'and', 'Francisco', 'two', 'Centinels', '.']

## Vectorization은 데이터를 벡터화해서 연산하는 것을 일컫는다.
# 이것의 장점은 반복문을 통해 연산 했을 때보다 속도가 훨씬 빠르다는 것이다.
# 특히나 데이터의 값이 많아질수록 속도의 차이는 더욱 심해진다.

In [15]:
#벡터화 하기
vect1 = []
#문장 사전 개수만큼 반복(62번)
for word in data:
    # 4번째 문장안에 문장 사전내부의 단어가 있다면
    if word in sent1:
        #1로 마킹한다
        vect1.append(1)
    else:
        #없다면 0으로 마킹한다
        vect1.append(0)
print(vect1)
len(vect1)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


62

In [16]:
#위의 코드를 함수화 시키는 것
def wordToBinary(sentence, vocabulary):
    #문장을 출력해주는 부분을 추가했다
    print(sentence)
    vector = []
    for word in vocabulary:
        if word in sentence:
            vector.append(1)
        else:
            vector.append(0)
    return vector

In [17]:
# 문장들중 8번째 문장을 sent2 에 할당
sent2 = hamlet[7]
# 벡터화 시켜줌(함수 내부에 문장 출력 있음)
vect2 = wordToBinary(sent2, data)
#벡터 출력
print(vect2)

['Nay', 'answer', 'me', ':', 'Stand', '&', 'vnfold', 'your', 'selfe']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [18]:
# 위 부분들을 반복함
#16번째 문장
vect3 = wordToBinary(hamlet[15], data)
print(vect3)
#18번째 문장
vect4 = wordToBinary(hamlet[17], data)
print(vect4)
#20번째 문장
vect5 = wordToBinary(hamlet[19], data)
print(vect5)

['You', 'come', 'most', 'carefully', 'vpon', 'your', 'houre']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
["'", 'Tis', 'now', 'strook', 'twelue', ',', 'get', 'thee', 'to', 'bed', 'Francisco']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['For', 'this', 'releefe', 'much', 'thankes', ':', "'", 'Tis', 'bitter', 'cold', ',', 'And', 'I', 'am', 'sicke', 'at', 'heart']
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


# 전통적인 방식의 데이터베이스
## 컬럼의 숫자가 제한되어 있다.

# 텍스트 데이터
## 특성들이 많다.

# Vectorization의 장점

## 특성의 수를 줄여주는 효과
## 언어의 구문을 이해할 수 있다.

# Vectorization을 하는 방법

# 1. Bag Of Words : Unique Words, Word Frequency
# 2. TF-IDF : 

## TF = Term Frequency  
###         문장안에서 단어들이 나오는 빈도
###  TF = ----------------------------------
###          문장안에서 단어들의 총 갯수

## IDF = Inverse Document Frequence
###               (문서 - document) 문장들의 총 갯수
### IDF = -------------------------------------------------
###         단어를 포함하는 (문서 - document) 문장들의 갯수

# BoW(Bag-of-Words)의 개념
## 애초에 컴퓨터는 인간이 아니기 때문에 언어를 이해할 방법이 없다고 봐도 된다. 아직까지는. 그래서 어떤 식으로든 1과 0 밖에 모르는 컴퓨터가 인간의 언어 사용 패턴을 최대한 이해하도록 여러가지 방법을 강구해야 하는데....
## 아무튼 BoW(Bag Of Words) 는 어휘의 빈도(개수)에 대해 통계적 언어 모델을 적용해서 나타낸 것이라 이해하면 된다.
https://hleecaster.com/nlp-bag-of-words-concept/

# TF-IDF(Term Frequency-Inverse Document Frequency)는 단어의 빈도와 역 문서 빈도(문서의 빈도에 특정 식을 취함)를 사용하여 DTM 내의 각 단어들마다 중요한 정도를 가중치로 주는 방법입니다.
## DTM 의 개념 https://wikidocs.net/24559

In [19]:
!pip install scikit-learn

You should consider upgrading via the 'd:\git\study\nltk\nltk\scripts\python.exe -m pip install --upgrade pip' command.


In [20]:
# 사이킷 런에서는 단어의 빈도를 Count하여 Vector로 만드는 CountVectorizer 클래스를 지원합니다
# 이는 앞에서 했던 Vectorization의 동작원리와 같다
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
#객체 만들어 주기
vectorizer = CountVectorizer()

In [22]:
# sents에 문장 5개를 join한다.

sents = []
sents.append(" ".join(hamlet[3]))
sents.append(" ".join(hamlet[7]))
sents.append(" ".join(hamlet[15]))
sents.append(" ".join(hamlet[17]))
sents.append(" ".join(hamlet[19]))
sents

['Enter Barnardo and Francisco two Centinels .',
 'Nay answer me : Stand & vnfold your selfe',
 'You come most carefully vpon your houre',
 "' Tis now strook twelue , get thee to bed Francisco",
 "For this releefe much thankes : ' Tis bitter cold , And I am sicke at heart"]

In [23]:
# Vectorization하는 과정(내부는 0과 1로 마킹되어 있음)
X = vectorizer.fit_transform(sents)

In [27]:
# 객체 내부에 저장되어 있는 sents의 이름들을 출력
print(vectorizer.get_feature_names())
# 단어 개수 출력
print(len(vectorizer.get_feature_names()))

['am', 'and', 'answer', 'at', 'barnardo', 'bed', 'bitter', 'carefully', 'centinels', 'cold', 'come', 'enter', 'for', 'francisco', 'get', 'heart', 'houre', 'me', 'most', 'much', 'nay', 'now', 'releefe', 'selfe', 'sicke', 'stand', 'strook', 'thankes', 'thee', 'this', 'tis', 'to', 'twelue', 'two', 'vnfold', 'vpon', 'you', 'your']
38


In [28]:
# 5*38 행렬생성
# 문장이 5개 단어가 38개 있음을 의미
X


<5x38 sparse matrix of type '<class 'numpy.int64'>'
	with 42 stored elements in Compressed Sparse Row format>

In [29]:
#List(리스트)를 Array(배열)로 변경할 때 사용하는 메서드가 toArray()이다.

X.toarray()

array([[0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [30]:
sents

['Enter Barnardo and Francisco two Centinels .',
 'Nay answer me : Stand & vnfold your selfe',
 'You come most carefully vpon your houre',
 "' Tis now strook twelue , get thee to bed Francisco",
 "For this releefe much thankes : ' Tis bitter cold , And I am sicke at heart"]

In [31]:
# regex를 이용하여 문장 처리(문장에서 문자가 아닌건 모두 공백으로 바꿔줌)
import re
#문장의 길이만큼 반복(5번)
for i in range(len(sents)):
    # 문장을 소문자로 변경
    sents[i] = sents[i].lower()
    #re.sub은 문자열을 치환하는 메소드이다.
    sents[i] = re.sub(r"\W", " ", sents[i])
sents

['enter barnardo and francisco two centinels  ',
 'nay answer me   stand   vnfold your selfe',
 'you come most carefully vpon your houre',
 '  tis now strook twelue   get thee to bed francisco',
 'for this releefe much thankes     tis bitter cold   and i am sicke at heart']

In [32]:
# 각각의 문장을 토큰화 해서 sent_tokens에 할당
sent_tokens = []
for sent in sents:
    # word_tokenize(리스트) 리스트 값을 집어넣어 줘야 한다.
    tokens = nltk.word_tokenize(sent)
    sent_tokens.append(tokens)

sent_tokens

[['enter', 'barnardo', 'and', 'francisco', 'two', 'centinels'],
 ['nay', 'answer', 'me', 'stand', 'vnfold', 'your', 'selfe'],
 ['you', 'come', 'most', 'carefully', 'vpon', 'your', 'houre'],
 ['tis', 'now', 'strook', 'twelue', 'get', 'thee', 'to', 'bed', 'francisco'],
 ['for',
  'this',
  'releefe',
  'much',
  'thankes',
  'tis',
  'bitter',
  'cold',
  'and',
  'i',
  'am',
  'sicke',
  'at',
  'heart']]

In [34]:
# 단어 빈도수 체크
# 즉 Bag-of-Words를 하는 과정이다.

# 단어의 빈도수를 저장할 wordfreq 딕셔너리 선언
wordfreq = {}
# 문장들을 토큰화한 sent_tokens의 개수만큼 반복(5번)
for sentence in sent_tokens:
    # 각 문장 내부의 각 단어들을
    for word in sentence:
        # wordfreq.keys()와 비교하여 존재하지 않는다면
        if word not in wordfreq.keys():
            # 키와 벨류를 생성
            wordfreq[word] = 1
        else:
            # wordfreq.keys()와 비교하여 존재 한다면
            # 빈도수를 늘려준다
            wordfreq[word] += 1

wordfreq

{'enter': 1,
 'barnardo': 1,
 'and': 2,
 'francisco': 2,
 'two': 1,
 'centinels': 1,
 'nay': 1,
 'answer': 1,
 'me': 1,
 'stand': 1,
 'vnfold': 1,
 'your': 2,
 'selfe': 1,
 'you': 1,
 'come': 1,
 'most': 1,
 'carefully': 1,
 'vpon': 1,
 'houre': 1,
 'tis': 2,
 'now': 1,
 'strook': 1,
 'twelue': 1,
 'get': 1,
 'thee': 1,
 'to': 1,
 'bed': 1,
 'for': 1,
 'this': 1,
 'releefe': 1,
 'much': 1,
 'thankes': 1,
 'bitter': 1,
 'cold': 1,
 'i': 1,
 'am': 1,
 'sicke': 1,
 'at': 1,
 'heart': 1}

## lamda는 함수를 한줄로 만들어 주는 신기한 녀석
## lambda 인자 : 표현식 이 기본 형태
# ex)함수가 이렇게 생겼다면
--def hap(x, y):

-   return x + y

--hap(10, 20)
-    30
# ex)lamda는 이렇게 생겼다.
--(lambda x,y: x + y)(10, 20)
-  30

In [35]:
# sorted(정렬할 데이터, key 파라미터, reverse 파라미터)
# 이 부분의 람다식이 어떻게 동작하는지는 이해하지 못했음 아는분 있으면 알려주길 바람
# 결국 단어 빈도수를 정렬하라는 것
sort_wordfreq = sorted(wordfreq.items(), key = lambda kv:(kv[1], kv[0]), reverse = True)

In [36]:
sort_wordfreq

[('your', 2),
 ('tis', 2),
 ('francisco', 2),
 ('and', 2),
 ('you', 1),
 ('vpon', 1),
 ('vnfold', 1),
 ('two', 1),
 ('twelue', 1),
 ('to', 1),
 ('this', 1),
 ('thee', 1),
 ('thankes', 1),
 ('strook', 1),
 ('stand', 1),
 ('sicke', 1),
 ('selfe', 1),
 ('releefe', 1),
 ('now', 1),
 ('nay', 1),
 ('much', 1),
 ('most', 1),
 ('me', 1),
 ('i', 1),
 ('houre', 1),
 ('heart', 1),
 ('get', 1),
 ('for', 1),
 ('enter', 1),
 ('come', 1),
 ('cold', 1),
 ('centinels', 1),
 ('carefully', 1),
 ('bitter', 1),
 ('bed', 1),
 ('barnardo', 1),
 ('at', 1),
 ('answer', 1),
 ('am', 1)]

In [37]:
# 빈도수 데이터가 너무 많으니 5개만 잘라서 가장 많은 빈도를 5개 출력
most_freq = []
for word in sort_wordfreq[:5]:
    most_freq.append(word[0])
most_freq

['your', 'tis', 'francisco', 'and', 'you']

| 단어 | 총 문장 | 빈도수 | 총 문장 / 빈도수 |
| word | total sentences | sentence has word | total sents / sent has word |
| --- | --- | --- | --- |
| and | 5 | 2 | 2.5 |
| francisco | 5 | 2 | 2.5 |
| tis | 5 | 2 | 2.5 |
| you | 5 | 1 | 5 |
| your | 5 | 2 |  2.5 |

즉 idf 구하는 것임

In [38]:
# 이 부분은 이해가 잘 가지 않는다.
# 내부의 로직이 어렵다 나중에 다시 리마인드 하자
# 대충 기능만 보면 most_freq에서 token 가져와서 sent리스트와 비교하여 있으면 1씩 추가시켜주는 것임
import numpy as np 

word_idf_values = {}
for token in most_freq:
    sent_has_word = 0
    for sent in sent_tokens:
        if token in sent:
            sent_has_word += 1
        # 아래부분이 이해 안감
        word_idf_values[token] = np.log(len(sents) / (1 + sent_has_word))

word_idf_values

{'your': 0.5108256237659907,
 'tis': 0.5108256237659907,
 'francisco': 0.5108256237659907,
 'and': 0.5108256237659907,
 'you': 0.9162907318741551}

In [39]:
# 여기는 tf 구하는 로직이다.
# 여기도 아직 이해가 부족하다.
word_tf_values = {}
# 5번 반복
for token in most_freq:
    sent_tf_vector = []
    for sent in sent_tokens:
        doc_freq = 0
        for word in sent:
            if token == word:
                # 문장 내부의 단어와 빈도수 단어가 같다면 doc_freq에 1을 추가함
                doc_freq += 1
        word_tf = doc_freq / len(sent)
        sent_tf_vector.append(word_tf)
    # 딕셔너리 형태로 token마다 중요도를 만들어중
    word_tf_values[token] = sent_tf_vector

word_tf_values

{'your': [0.0, 0.14285714285714285, 0.14285714285714285, 0.0, 0.0],
 'tis': [0.0, 0.0, 0.0, 0.1111111111111111, 0.07142857142857142],
 'francisco': [0.16666666666666666, 0.0, 0.0, 0.1111111111111111, 0.0],
 'and': [0.16666666666666666, 0.0, 0.0, 0.0, 0.07142857142857142],
 'you': [0.0, 0.0, 0.14285714285714285, 0.0, 0.0]}

In [59]:
# tf-idf 고려한 중요도?
tfidf_values = []

for token in word_tf_values.keys():
    tfidf_sentences = []
    for tf_sentence in word_tf_values[token]:
        tf_idf_score = tf_sentence * word_idf_values[token]
        tfidf_sentences.append(tf_idf_score)
    tfidf_values.append(tfidf_sentences)

tfidf_values

[[0.0, 0.07297508910942724, 0.07297508910942724, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.05675840264066563, 0.03648754455471362],
 [0.08513760396099845, 0.0, 0.0, 0.05675840264066563, 0.0],
 [0.08513760396099845, 0.0, 0.0, 0.0, 0.03648754455471362],
 [0.0, 0.0, 0.13089867598202215, 0.0, 0.0]]

In [60]:
tf_idf_model = np.asarray(tfidf_values)
tf_idf_model

array([[0.        , 0.07297509, 0.07297509, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.0567584 , 0.03648754],
       [0.0851376 , 0.        , 0.        , 0.0567584 , 0.        ],
       [0.0851376 , 0.        , 0.        , 0.        , 0.03648754],
       [0.        , 0.        , 0.13089868, 0.        , 0.        ]])

In [61]:
type(tf_idf_model)

numpy.ndarray

In [62]:
tf_idf_model = np.transpose(tf_idf_model)
tf_idf_model

array([[0.        , 0.        , 0.0851376 , 0.0851376 , 0.        ],
       [0.07297509, 0.        , 0.        , 0.        , 0.        ],
       [0.07297509, 0.        , 0.        , 0.        , 0.13089868],
       [0.        , 0.0567584 , 0.0567584 , 0.        , 0.        ],
       [0.        , 0.03648754, 0.        , 0.03648754, 0.        ]])

In [40]:
# 위에서 했던 고생을 한방에 해주는 고마운 사이킷 런
from sklearn.feature_extraction.text import TfidfVectorizer

In [41]:
# 객체 만들고
vectorizer = TfidfVectorizer()

In [42]:
sents

['enter barnardo and francisco two centinels  ',
 'nay answer me   stand   vnfold your selfe',
 'you come most carefully vpon your houre',
 '  tis now strook twelue   get thee to bed francisco',
 'for this releefe much thankes     tis bitter cold   and i am sicke at heart']

In [43]:
# fit_transform 메서드에 문장을 집어넣으면 벡터화 해줌
X = vectorizer.fit_transform(sents)

In [45]:

print(vectorizer.get_feature_names())
print(len(vectorizer.get_feature_names()))

['am', 'and', 'answer', 'at', 'barnardo', 'bed', 'bitter', 'carefully', 'centinels', 'cold', 'come', 'enter', 'for', 'francisco', 'get', 'heart', 'houre', 'me', 'most', 'much', 'nay', 'now', 'releefe', 'selfe', 'sicke', 'stand', 'strook', 'thankes', 'thee', 'this', 'tis', 'to', 'twelue', 'two', 'vnfold', 'vpon', 'you', 'your']
38


In [69]:
# 벡터화 한거 출력해보면
X.toarray()

array([[0.        , 0.35038823, 0.        , 0.        , 0.43429718,
        0.        , 0.        , 0.        , 0.43429718, 0.        ,
        0.        , 0.43429718, 0.        , 0.35038823, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.43429718, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.38775666, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.38775666, 0.        , 0.        ,
        0.38775666, 0.        , 0.        , 0.38775666, 0.        ,
        0.38775666, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.38775666,
   

In [ ]:
#끝